name = "diabloweb"
compatibility_date = "2023-10-30"

# Pages configuration - this should be at the top level for Pages
pages_build_output_dir = "build"

[env.production]
account_id = "your-account-id"

# Environment variables (if needed)
[env.production.vars]
NODE_ENV = "production"
